//--------------------------------------------------------------------------------
// Auto-generated by Migen (3ffd64c) & LiteX (7179d88) on 2022-07-12 13:30:59
//--------------------------------------------------------------------------------
module SelfTrigger(
	input wire rst,
	input wire [13:0] data_in,
	output reg out,
	output reg [13:0] data_out,
	input wire adc_frame_clk,
	input wire adc_frame_rst
);

reg [13:0] __main___reg_trigger0 = 14'd0;
reg [13:0] __main___reg_trigger1 = 14'd0;
reg [13:0] __main___reg_trigger2 = 14'd0;
reg [13:0] __main___reg_trigger3 = 14'd0;
reg [13:0] __main___reg_trigger4 = 14'd0;
reg [13:0] __main___reg_trigger5 = 14'd0;
reg [13:0] __main___reg_trigger6 = 14'd0;
reg [13:0] __main___reg_trigger7 = 14'd0;
reg [13:0] __main___reg_trigger8 = 14'd0;
reg [13:0] __main___reg_trigger9 = 14'd0;
reg [13:0] __main___reg_trigger10 = 14'd0;
reg [13:0] __main___reg_trigger11 = 14'd0;
reg [13:0] __main___reg_trigger12 = 14'd0;
reg [13:0] __main___reg_trigger13 = 14'd0;
reg [13:0] __main___reg_trigger14 = 14'd0;
reg [13:0] __main___reg_trigger15 = 14'd0;
reg [13:0] __main___reg_trigger16 = 14'd0;
reg [13:0] __main___reg_trigger17 = 14'd0;
reg [13:0] __main___reg_trigger18 = 14'd0;
reg [13:0] __main___reg_trigger19 = 14'd0;
reg [13:0] __main___reg_trigger20 = 14'd0;
reg [13:0] __main___reg_trigger21 = 14'd0;
reg [13:0] __main___reg_trigger22 = 14'd0;
reg [13:0] __main___reg_trigger23 = 14'd0;
reg [13:0] __main___reg_trigger24 = 14'd0;
reg [13:0] __main___reg_trigger25 = 14'd0;
reg [13:0] __main___reg_trigger26 = 14'd0;
reg [13:0] __main___reg_trigger27 = 14'd0;
reg [13:0] __main___reg_trigger28 = 14'd0;
reg [13:0] __main___reg_trigger29 = 14'd0;
reg [13:0] __main___reg_trigger30 = 14'd0;
reg [13:0] __main___reg_trigger31 = 14'd0;
reg [13:0] __main___reg_trigger32 = 14'd0;
reg [13:0] __main___reg_trigger33 = 14'd0;
reg [13:0] __main___reg_trigger34 = 14'd0;
reg [13:0] __main___reg_trigger35 = 14'd0;
reg [13:0] __main___reg_trigger36 = 14'd0;
reg [13:0] __main___reg_trigger37 = 14'd0;
reg [13:0] __main___reg_trigger38 = 14'd0;
reg [13:0] __main___reg_trigger39 = 14'd0;
reg [13:0] __main___reg_trigger40 = 14'd0;
reg [13:0] __main___reg_trigger41 = 14'd0;
reg [13:0] __main___reg_trigger42 = 14'd0;
reg [13:0] __main___reg_trigger43 = 14'd0;
reg [13:0] __main___reg_trigger44 = 14'd0;
reg [13:0] __main___reg_trigger45 = 14'd0;
reg [13:0] __main___reg_trigger46 = 14'd0;
reg [13:0] __main___reg_trigger47 = 14'd0;
reg [13:0] __main___reg_trigger48 = 14'd0;
reg [13:0] __main___reg_trigger49 = 14'd0;
reg [13:0] __main___reg_trigger50 = 14'd0;
reg [13:0] __main___reg_trigger51 = 14'd0;
reg [13:0] __main___reg_trigger52 = 14'd0;
reg [13:0] __main___reg_trigger53 = 14'd0;
reg [13:0] __main___reg_trigger54 = 14'd0;
reg [13:0] __main___reg_trigger55 = 14'd0;
reg [13:0] __main___reg_trigger56 = 14'd0;
reg [13:0] __main___reg_trigger57 = 14'd0;
reg [13:0] __main___reg_trigger58 = 14'd0;
reg [13:0] __main___reg_trigger59 = 14'd0;


always @(posedge adc_frame_clk) begin
	__main___reg_trigger1 <= __main___reg_trigger0;
	__main___reg_trigger2 <= __main___reg_trigger1;
	__main___reg_trigger3 <= __main___reg_trigger2;
	__main___reg_trigger4 <= __main___reg_trigger3;
	__main___reg_trigger5 <= __main___reg_trigger4;
	__main___reg_trigger6 <= __main___reg_trigger5;
	__main___reg_trigger7 <= __main___reg_trigger6;
	__main___reg_trigger8 <= __main___reg_trigger7;
	__main___reg_trigger9 <= __main___reg_trigger8;
	__main___reg_trigger10 <= __main___reg_trigger9;
	__main___reg_trigger11 <= __main___reg_trigger10;
	__main___reg_trigger12 <= __main___reg_trigger11;
	__main___reg_trigger13 <= __main___reg_trigger12;
	__main___reg_trigger14 <= __main___reg_trigger13;
	__main___reg_trigger15 <= __main___reg_trigger14;
	__main___reg_trigger16 <= __main___reg_trigger15;
	__main___reg_trigger17 <= __main___reg_trigger16;
	__main___reg_trigger18 <= __main___reg_trigger17;
	__main___reg_trigger19 <= __main___reg_trigger18;
	__main___reg_trigger20 <= __main___reg_trigger19;
	__main___reg_trigger21 <= __main___reg_trigger20;
	__main___reg_trigger22 <= __main___reg_trigger21;
	__main___reg_trigger23 <= __main___reg_trigger22;
	__main___reg_trigger24 <= __main___reg_trigger23;
	__main___reg_trigger25 <= __main___reg_trigger24;
	__main___reg_trigger26 <= __main___reg_trigger25;
	__main___reg_trigger27 <= __main___reg_trigger26;
	__main___reg_trigger28 <= __main___reg_trigger27;
	__main___reg_trigger29 <= __main___reg_trigger28;
	__main___reg_trigger30 <= __main___reg_trigger29;
	__main___reg_trigger31 <= __main___reg_trigger30;
	__main___reg_trigger32 <= __main___reg_trigger31;
	__main___reg_trigger33 <= __main___reg_trigger32;
	__main___reg_trigger34 <= __main___reg_trigger33;
	__main___reg_trigger35 <= __main___reg_trigger34;
	__main___reg_trigger36 <= __main___reg_trigger35;
	__main___reg_trigger37 <= __main___reg_trigger36;
	__main___reg_trigger38 <= __main___reg_trigger37;
	__main___reg_trigger39 <= __main___reg_trigger38;
	__main___reg_trigger40 <= __main___reg_trigger39;
	__main___reg_trigger41 <= __main___reg_trigger40;
	__main___reg_trigger42 <= __main___reg_trigger41;
	__main___reg_trigger43 <= __main___reg_trigger42;
	__main___reg_trigger44 <= __main___reg_trigger43;
	__main___reg_trigger45 <= __main___reg_trigger44;
	__main___reg_trigger46 <= __main___reg_trigger45;
	__main___reg_trigger47 <= __main___reg_trigger46;
	__main___reg_trigger48 <= __main___reg_trigger47;
	__main___reg_trigger49 <= __main___reg_trigger48;
	__main___reg_trigger50 <= __main___reg_trigger49;
	__main___reg_trigger51 <= __main___reg_trigger50;
	__main___reg_trigger52 <= __main___reg_trigger51;
	__main___reg_trigger53 <= __main___reg_trigger52;
	__main___reg_trigger54 <= __main___reg_trigger53;
	__main___reg_trigger55 <= __main___reg_trigger54;
	__main___reg_trigger56 <= __main___reg_trigger55;
	__main___reg_trigger57 <= __main___reg_trigger56;
	__main___reg_trigger58 <= __main___reg_trigger57;
	__main___reg_trigger59 <= __main___reg_trigger58;
	__main___reg_trigger0 <= data_in;
	data_out <= __main___reg_trigger59;
	if (((__main___reg_trigger0 - __main___reg_trigger19) > 6'd40)) begin
		out <= 1'd1;
	end else begin
		if (((__main___reg_trigger19 - __main___reg_trigger0) > 6'd40)) begin
			out <= 1'd1;
		end else begin
			out <= 1'd0;
		end
	end
	if (adc_frame_rst) begin
		out <= 1'd0;
		data_out <= 14'd0;
		__main___reg_trigger0 <= 14'd0;
		__main___reg_trigger1 <= 14'd0;
		__main___reg_trigger2 <= 14'd0;
		__main___reg_trigger3 <= 14'd0;
		__main___reg_trigger4 <= 14'd0;
		__main___reg_trigger5 <= 14'd0;
		__main___reg_trigger6 <= 14'd0;
		__main___reg_trigger7 <= 14'd0;
		__main___reg_trigger8 <= 14'd0;
		__main___reg_trigger9 <= 14'd0;
		__main___reg_trigger10 <= 14'd0;
		__main___reg_trigger11 <= 14'd0;
		__main___reg_trigger12 <= 14'd0;
		__main___reg_trigger13 <= 14'd0;
		__main___reg_trigger14 <= 14'd0;
		__main___reg_trigger15 <= 14'd0;
		__main___reg_trigger16 <= 14'd0;
		__main___reg_trigger17 <= 14'd0;
		__main___reg_trigger18 <= 14'd0;
		__main___reg_trigger19 <= 14'd0;
		__main___reg_trigger20 <= 14'd0;
		__main___reg_trigger21 <= 14'd0;
		__main___reg_trigger22 <= 14'd0;
		__main___reg_trigger23 <= 14'd0;
		__main___reg_trigger24 <= 14'd0;
		__main___reg_trigger25 <= 14'd0;
		__main___reg_trigger26 <= 14'd0;
		__main___reg_trigger27 <= 14'd0;
		__main___reg_trigger28 <= 14'd0;
		__main___reg_trigger29 <= 14'd0;
		__main___reg_trigger30 <= 14'd0;
		__main___reg_trigger31 <= 14'd0;
		__main___reg_trigger32 <= 14'd0;
		__main___reg_trigger33 <= 14'd0;
		__main___reg_trigger34 <= 14'd0;
		__main___reg_trigger35 <= 14'd0;
		__main___reg_trigger36 <= 14'd0;
		__main___reg_trigger37 <= 14'd0;
		__main___reg_trigger38 <= 14'd0;
		__main___reg_trigger39 <= 14'd0;
		__main___reg_trigger40 <= 14'd0;
		__main___reg_trigger41 <= 14'd0;
		__main___reg_trigger42 <= 14'd0;
		__main___reg_trigger43 <= 14'd0;
		__main___reg_trigger44 <= 14'd0;
		__main___reg_trigger45 <= 14'd0;
		__main___reg_trigger46 <= 14'd0;
		__main___reg_trigger47 <= 14'd0;
		__main___reg_trigger48 <= 14'd0;
		__main___reg_trigger49 <= 14'd0;
		__main___reg_trigger50 <= 14'd0;
		__main___reg_trigger51 <= 14'd0;
		__main___reg_trigger52 <= 14'd0;
		__main___reg_trigger53 <= 14'd0;
		__main___reg_trigger54 <= 14'd0;
		__main___reg_trigger55 <= 14'd0;
		__main___reg_trigger56 <= 14'd0;
		__main___reg_trigger57 <= 14'd0;
		__main___reg_trigger58 <= 14'd0;
		__main___reg_trigger59 <= 14'd0;
	end
end

endmodule
